service: lambda-shell

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  memorySize: 128
  timeout: 300

package:
  include:
    - src/**

functions:
  exec:
    handler: src/index.handle